services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    environment:
      - TZ=Europe/Minsk
  bot:
    build:
      context: .
      dockerfile: ./bot/Dockerfile
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - BOT_LOG_FILE_PATH=/app/bot.log
      - TZ=Europe/Minsk
    depends_on:
      - redis
    volumes:
      - ./bot:/app
    command: sh -c "APP_TYPE=bot python main.py"

  celery:
    build:
      context: .
      dockerfile: ./celery_tasker/Dockerfile
    volumes:
      - ./celery_tasker:/app
    depends_on:
      - redis
    command: celery -A tasks.celery_app worker --loglevel=info

  celery-beat:
    build:
      context: .
      dockerfile: ./celery_tasker/Dockerfile
    volumes:
      - ./celery_tasker:/app
    depends_on:
      - redis
    command: celery -A tasks.celery_app beat --loglevel=info

  flower:
    build:
      context: .
      dockerfile: ./flower/Dockerfile
    volumes:
      - ./celery_tasker:/app
    ports:
      - "5555:5555"
    depends_on:
      - celery